#pragma once
/*THE UNITS USED FOR THIS SIMULATION ARE AS FOLLOWS:
  - METERS
  - KILOGRAMS
  - NEWTONS
  - KM/HR
  - SECONDS, HOURS
  - PSI
  - PASCALS*/
//ROCKET HULL MATERIALS + THEIR DENSITIES
#define ALUMINUM 2700 //kg/m^3
#define AEROSPACEGRADEALUMINUM 2810 //kg/m^3
#define TITANIUM 4507 //kg/m^3
#define STAINLESSSTEEL 7900 //kg/m^3
//ROCKET ENGINE MATERIALS + THEIR DENSITIES
#define NICKEL 8908 //kg/m^3
#define IRON 7874 //kg/m^3
#define COBALT 8900 //kg/m^3
//ROCKET OXIDIZERS AND PROPELLANTS
#define LIQUIDFLUORINE 1505 //kg/m^3
#define LIQUIDOXYGEN 1141 //kg/m^3
#define LIQUIDHYDROGEN 71 //kg/m^3
#define KEROSENSE 804 //kg/m^3
#define METER 0.7f //World unit to meter unit